<a href="https://colab.research.google.com/github/stac-bot/Pytorch-for-Deep-Learning/blob/main/pytorch101(tensors).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print('Hello excited for pytorch for deep learning!')

Hello excited for pytorch for deep learning!


## intro to pytorch Fundamental

In [3]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.12.1+cu113


#### introduction to tensors

creating tensors

In [4]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# get tensor back as python integer
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([7,5])
vector

tensor([7, 5])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX 
MATRIX = torch.tensor([[4,5],
                       [7,6]])
MATRIX

tensor([[4, 5],
        [7, 6]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([7, 6])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR CAN BE ANY DIMENSIONS 
TENSOR = torch.tensor([[[2,3,4],
                        [3,5,6],
                        [6,7,8]]])
TENSOR

tensor([[[2, 3, 4],
         [3, 5, 6],
         [6, 7, 8]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
# DIMENSIONS STUFF ACCESS IS TRICKY
TENSOR[0][2][1]

tensor(7)

#### random tensors
 **creating tensor**

Random tensors are important because the way many neural network learns in that they start with tensors full of random numbers to represent the data.<br>
`start with random numbers--> look at data --> update random numbers --> look at the data --> update random numbers`

In [18]:
from torch import random
## random tensor of shape (3,4)
random_tensor = torch.randn(3,4)
random_tensor

tensor([[-1.0318, -0.1720, -0.6675, -0.9441],
        [-0.5077,  0.1677, -0.3295, -0.0525],
        [ 1.0664,  1.2382,  1.3357, -1.3479]])

In [19]:
# remember tensors can be of any dimension
random_tensor = torch.randn(10,10,10)
random_tensor

tensor([[[-4.5174e-01,  6.0771e-02,  1.4007e+00, -1.8419e+00,  1.5601e+00,
          -6.8191e-01, -1.2196e+00, -1.2248e-01, -9.0098e-01,  7.1884e-01],
         [ 2.8398e-01, -1.0642e-01,  1.8510e-01, -1.6374e+00, -1.1870e+00,
           2.3872e+00, -9.9966e-01,  4.3739e-01,  1.3963e+00,  4.1029e-02],
         [-8.5847e-01, -8.4309e-01, -3.0423e-01, -2.3228e+00,  9.8175e-01,
          -7.0377e-03, -1.5342e+00,  1.7407e-01, -2.7562e-01,  1.0947e+00],
         [ 1.1929e-01,  4.3944e-01, -6.9146e-01,  2.1049e+00, -1.1480e-01,
           5.2594e-01,  3.8302e-01, -1.3316e-01, -1.8324e+00, -4.9160e-01],
         [-5.9043e-01, -5.3294e-01,  4.3618e-01,  8.4481e-01, -1.9330e-01,
           1.7770e-01, -1.5046e+00,  4.2790e-01,  1.9476e-01, -6.4495e-01],
         [-6.2013e-01,  4.7170e-02, -2.0857e+00,  2.1834e-01, -3.8974e-01,
           6.9305e-01,  8.9245e-01,  1.9766e-01, -2.8109e-01,  7.8443e-01],
         [-4.6639e-01,  2.8193e-01, -2.5003e-01, -3.9081e-01,  6.0147e-02,
           1.0342e+

In [20]:
# random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3)) # height , width, color channels
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

`Take away : tensor can represent any data such as image as above`

In [21]:
random_tensor = torch.rand(size=(3,4)) # size can be used or otherwise

#### zeros and ones

In [22]:
# creating a tesor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# creating a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
zeros[0][1]*random_tensor[0][1]

tensor(0.)

In [25]:
random_tensor.dtype

torch.float32

#### creating a range of tensors and tensors-like

In [26]:
# use torch.range() and get deprecated message, use torch.arange()
range_tensor = torch.arange(start=0, end= 1000, step = 77)
range_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [27]:
# creating tensors-like to create similar size tensor
ten_zeros = torch.zeros_like(input = range_tensor)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor  Datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with Pytorch & Deep Learning
1. dtype
2. shape
3. device

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,4.0,5.0],
                               dtype=None,
                               device=None,
                               requires_grad= False)
float_32_tensor

tensor([3., 4., 5.])

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [30]:
(float_32_tensor * float_16_tensor).dtype

torch.float32

tensor attributes 

In [31]:
float_64_tensor = float_32_tensor.type(torch.float64)
float_64_tensor

tensor([3., 4., 5.], dtype=torch.float64)

In [32]:
int32_tensor = float_32_tensor.type(torch.int32)
int32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [33]:
# aaah!! still works but runs into the issue and is caveats of tensors
(int32_tensor * float_16_tensor)

tensor([ 9., 16., 25.], dtype=torch.float16)

In [34]:
long_tensor = float_32_tensor.type(torch.long)
long_tensor

tensor([3, 4, 5])

In [35]:
(long_tensor * int32_tensor)

tensor([ 9, 16, 25])

#### Getting information from tensors

In [36]:
# creatting a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4464, 0.5126, 0.3638, 0.4988],
        [0.6511, 0.9382, 0.2750, 0.5838],
        [0.4622, 0.6720, 0.7045, 0.5008]])

In [37]:
some_tensor.size, some_tensor.shape # both give the same thing

(<function Tensor.size>, torch.Size([3, 4]))

In [38]:
# Find out details about some tensors
print(f'Datatype of tensor:',{some_tensor.dtype})
print(f'Size of the tensor:',{some_tensor.size()})
print(f'device on which tensor is:',{some_tensor.device})

Datatype of tensor: {torch.float32}
Size of the tensor: {torch.Size([3, 4])}
device on which tensor is: {device(type='cpu')}


In [39]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
some_tensor = some_tensor.to(device)

In [40]:
# changing the device on which tensor runs on  
print(f'device on which tensor is:',{some_tensor.device})

device on which tensor is: {device(type='cuda', index=0)}


#### manipulating Tensors


##### Tensor operations include:
* Addition
* Sub
* Multiplication(ele-wise)
* Division
* Matrix multiplication

In [41]:
# create a tensor and not reassigning
tensor = torch.tensor([2,3,4])
print(tensor)
print(tensor + 10)
print(tensor - 19)
print(tensor* 2)

tensor([2, 3, 4])
tensor([12, 13, 14])
tensor([-17, -16, -15])
tensor([4, 6, 8])


In [42]:
# try in-built function
tensor, torch.mul(tensor,3)

(tensor([2, 3, 4]), tensor([ 6,  9, 12]))

#### Matrix Multiplication 
* two main ways of performing multiplication in neural networks and deep learning
1. element-wise
2. matrix-wise(dot-product)

In [43]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f'Equals:',{tensor*tensor,})

tensor([2, 3, 4]) * tensor([2, 3, 4])
Equals: {tensor([ 4,  9, 16])}


In [44]:
# dot-product
torch.matmul(tensor,tensor)

tensor(29)

`note: if torch has some built-in fuction for common stuff that mean they are the faster than conventional way`

In [45]:
%%time
value = 0
for i in range(ken(tensor)):
  value+= tensor[i] * tensor[i]
print(value)

NameError: ignored

In [46]:
tensor @ tensor #'@' same as multiplication

tensor(29)

In [47]:
# trying to change the device on which the tensor is 
torch.matmul(tensor,tensor)

tensor(29)

#### rule of matmul
1. The **inner dimension** must match
2. Result matrix has the shape of **outer dimension**


In [49]:
# rule one should be statisfied else error occurs
torch.matmul(torch.rand(2,3),torch.rand(2,3))

RuntimeError: ignored

In [148]:
# rule one statisfied
torch.matmul(torch.rand(2,2),torch.rand(2,3))

tensor([[0.3736, 0.2306, 0.4147],
        [0.2012, 0.1790, 0.1697]])

In [149]:
# rule 2 statisfied
torch.matmul(torch.rand(3,10),torch.rand(10,3))

tensor([[1.2830, 2.0798, 2.0535],
        [1.8053, 2.6818, 3.1109],
        [2.4111, 3.7451, 3.9128]])

### one of the most common errors in deep learning: shape errrors

http://matrixmultiplication.xyz/

In [150]:
tensorA = torch.tensor([[3,4],[2,4],[7,8]])
tensorB = torch.tensor([[3,4],[2,4],[7,8]])

print(tensorA.size(),tensorB.size())
print('just broke the --> rule one inner sides must match')
print(tensorA@tensorB)


torch.Size([3, 2]) torch.Size([3, 2])
just broke the --> rule one inner sides must match


RuntimeError: ignored

to fix our tensor shape issues, we can manipulate the shape of one of our tensors using transpose of matrix<br>
A **transpose** switches the axes or dimension of a given tensor.

In [152]:
tensorA.T.shape, tensorB.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [153]:
tensorA.T @ tensorB
# change with transpose to abide by the two rules above
torch.matmul(tensorA,tensorB.T)

tensor([[ 25,  22,  53],
        [ 22,  20,  46],
        [ 53,  46, 113]])

In [154]:
# let's visualize what going on

## Finding min, max, mean, sum etc (aggregation) 

In [155]:
#find min
x = torch.arange(1,100)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99])

In [156]:
torch.min(x), torch.max(x)

(tensor(1), tensor(99))

In [157]:
x.min(), x.max()

(tensor(1), tensor(99))

In [158]:
# find mean - note the torch.mean() require torch.float32 datatype
torch.mean(x)

RuntimeError: ignored

In [159]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

## Find the positional min and max returnning index


In [160]:
x = torch.arange(0,101,10)

In [161]:
x.argmin(), x[0]

(tensor(0), tensor(0))

In [162]:
x.argmax(), x[10]

(tensor(10), tensor(100))

## Reshaping, stacking, squeezing and unsqueezing tensors
 * Reshaping- reshapes an input tesnor to a defined shape
 * view - Return a view of input tensor of certain shape but keep the same memory as the original tensor
 * Squeezing - removes all `1` dimension from tensor
 * unsqueeze - add a `1` dimension to target tensor
 * permute - Retrun a view of the inputs with dimensions permuted (swapped) in certain way 

In [163]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [164]:
# Add an extra dimension
x_reshaped = x.reshape(9,1) # reshaped has to be compatible with the size
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [165]:
# change the view
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [166]:
# view is same as similar reshape, but share the same space as x
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [167]:
# changing z change x
z[0,5] = 8
z , x

(tensor([[1., 2., 3., 4., 5., 8., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 8., 7., 8., 9.]))

In [168]:
# stack tensors on the top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked 


tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [169]:
x_reshaped = x.reshape(9,1)

In [170]:
# torch.squeeze() - remove all the dimension from a target tensor
x_reshaped.squeeze()
x_reshaped.shape, x_reshaped.squeeze().shape

(torch.Size([9, 1]), torch.Size([9]))

In [171]:
#let's visualize the torch.squeeze()
# normal tensor
print(f'Previous tensor: {x_reshaped} \ntensor Shape:{x_reshaped.shape}')

# After squeezing tensor
print(f'After torch.squeeze() is applied \nNew squeezed tensor: {x_reshaped.squeeze()} \nShape is: {x_reshaped.squeeze().shape}')

Previous tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [8.],
        [7.],
        [8.],
        [9.]]) 
tensor Shape:torch.Size([9, 1])
After torch.squeeze() is applied 
New squeezed tensor: tensor([1., 2., 3., 4., 5., 8., 7., 8., 9.]) 
Shape is: torch.Size([9])


In [172]:
# homework unsqueezing and visualizing

##### permute tensors 


Rearranging the dimension of tensors

In [173]:
x_original = torch.rand(size=(224,224,3)) #

#permute the original tensor to rearrange the axis (on dim) order
x_permuted = x_original.permute(2,0,1) # shift axis 0->1, 1->2, 2->0

print(f'the original tensor: {x_original.shape}')
print(f'the permuted tensor: {x_permuted.shape}')

the original tensor: torch.Size([224, 224, 3])
the permuted tensor: torch.Size([3, 224, 224])


In [174]:
x_original[0,0,1],x_permuted[0,0,1]
x_original[0,0,1] = 234234
x_original[0,0,1],x_permuted[0,0,1]

(tensor(234234.), tensor(0.7946))

#### indexing 

indexing with numpy is same as Numpy Indexing

In [175]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [176]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [177]:
# Let's index on the middle bracket dim=1
x[0,0]
x[0][0]

tensor([1, 2, 3])

In [178]:
# Let's index on the inner bracket (last dimension)
x[0][0][0]
x[0,0,1] 


tensor(2)

In [179]:
# Let's get number 9 
x[0][2][2]

tensor(9)

In [180]:
# You can also use ";" to select "all" of the target dimension
# Let's get all the values of the 0th and 1th dim and just first of the 2nd dim 
x[:,:,0]

tensor([[1, 4, 7]])

In [181]:
# Let's get all the values of the 0th and last value from 1nd dim and 2nd first of the 2nd dim 
x[:,-1,-1]

tensor([9])

In [182]:
# Let's get all the values from 1st dim and the just 1st 
x[0,:,1]

tensor([2, 5, 8])

## pytorch tensors & Numpy

`warning: when converting from numpy-->pytorch, pytorch by default reflects numpy's default datatype of float64 unless specified otherwise`

In [183]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.,10.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [184]:
# chaning the value of the array, what will this do to the tensor
array = array + 3
tensor, array
# note tensor did't change; they don't share memory

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64),
 array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [185]:
# Tensor to Numpy array
tensor = torch.ones(1)
array = tensor.numpy()
tensor, array

(tensor([1.]), array([1.], dtype=float32))

## Reproducibility (trying to take random out of random)


To be succtint neural network learns:<br>
`start with random number --> tensor operations -> update random number to try and make them representing the same data-> again->again`<br>

`# when running into error with tensor sing a song 'what,what,where'`
* "what shape are my tensors? what dataype are they and where are they stored? what shape what datatype, where where where"

In [186]:
# using random seed 
# this is random but reproducible tensor
random.seed = 32
tensor = torch.rand(3,3)
tensor

tensor([[0.3204, 0.4905, 0.9574],
        [0.0178, 0.5160, 0.5669],
        [0.7521, 0.7024, 0.8072]])

In [187]:
tensor==tensor

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [188]:
# using random seed 
# this is random but reproducible tensor 
# seed works for just one block
random.seed = 32
tensorA = torch.rand(3,3)

tensorB = torch.rand(3,3)
tensorA == tensorB 
# see doesn't work why?

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [189]:
# seed works for just one block
random.seed = 32
torch.manual_seed(random.seed) # call for random seed
tensorA = torch.rand(3,3)

torch.manual_seed(random.seed) # call for random seed
tensorB = torch.rand(3,3)
tensorA == tensorB 
# haa! now works , tensors are same

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

`trick: to know the shape of tensor is the numbet(#) of comma inside[] + 1, but apply quickly to small shapes of tensor`

In [190]:
import torch
T = torch.rand(size=(3,4))
T.ndim, T.shape

(2, torch.Size([3, 4]))

In [191]:
T1 = torch.tensor([3.0,4.0,5.0],
                  dtype=torch.float32,
                  device=None,
                  requires_grad = False)

In [192]:
T1.ndim, T1.shape, T1.dtype, T1.device


(1, torch.Size([3]), torch.float32, device(type='cpu'))

#### squeeze and unsqueeze with visualization

In [193]:
T = torch.zeros(2,1,3,1,3)
T.size()
T1 = torch.squeeze(T)
T1.shape,T.shape

(torch.Size([2, 3, 3]), torch.Size([2, 1, 3, 1, 3]))

In [194]:
T2 = torch.tensor([1,2,3,4])
T2,torch.unsqueeze(T2,1)


(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

##### spliting tensors 


In [195]:
T = torch.arange(14).reshape(2,7)
print(torch.tensor_split(T,4,dim=1)) # spliting and creating sub tensors

(tensor([[0, 1],
        [7, 8]]), tensor([[ 2,  3],
        [ 9, 10]]), tensor([[ 4,  5],
        [11, 12]]), tensor([[ 6],
        [13]]))


In [196]:
x1 = torch.rand(3,4)
x2 = torch.rand(4,3)
x2@x1 # multiplication of matrix

tensor([[0.9095, 0.2476, 0.5458, 0.7917],
        [1.0528, 0.3636, 0.3676, 0.7897],
        [1.2888, 0.4306, 0.6563, 1.1648],
        [0.8135, 0.3063, 0.2139, 0.5870]])

In [197]:
import random
random.seed = 42
x2 = torch.rand(4,3,3)

print(x2,'\n', x2.mT) # adjoint of matrix

tensor([[[0.7794, 0.0059, 0.1268],
         [0.7167, 0.3324, 0.8529],
         [0.3920, 0.5805, 0.2238]],

        [[0.5989, 0.0382, 0.1198],
         [0.1159, 0.5589, 0.4112],
         [0.9977, 0.5187, 0.9310]],

        [[0.2028, 0.6240, 0.4142],
         [0.9531, 0.6668, 0.5360],
         [0.1804, 0.0755, 0.3405]],

        [[0.7576, 0.2296, 0.2900],
         [0.0625, 0.9716, 0.9518],
         [0.2123, 0.5161, 0.4722]]]) 
 tensor([[[0.7794, 0.7167, 0.3920],
         [0.0059, 0.3324, 0.5805],
         [0.1268, 0.8529, 0.2238]],

        [[0.5989, 0.1159, 0.9977],
         [0.0382, 0.5589, 0.5187],
         [0.1198, 0.4112, 0.9310]],

        [[0.2028, 0.9531, 0.1804],
         [0.6240, 0.6668, 0.0755],
         [0.4142, 0.5360, 0.3405]],

        [[0.7576, 0.0625, 0.2123],
         [0.2296, 0.9716, 0.5161],
         [0.2900, 0.9518, 0.4722]]])


In [198]:
%%time
value=0
for i in range(len(x1)):
  value += x1[i]*x1[i]
value

CPU times: user 171 µs, sys: 0 ns, total: 171 µs
Wall time: 177 µs


tensor([1.4320, 0.1640, 0.5929, 1.2607])

In [199]:
%%time
torch.matmul(x1,x1.T)

CPU times: user 125 µs, sys: 0 ns, total: 125 µs
Wall time: 290 µs


tensor([[1.4852, 0.5405, 1.3932],
        [0.5405, 0.2109, 0.5278],
        [1.3932, 0.5278, 1.7536]])

#### setup and diagnostic code


In [200]:
# setup and diagnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [201]:
# Count number of devices
torch.cuda.device_count()

1

In [202]:
## 3. putting tensors (and models) on the GPU
tensor = torch.tensor([1,3,4])
print(tensor, tensor.device)

tensor([1, 3, 4]) cpu


In [203]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

tensor([1, 3, 4], device='cuda:0')


In [204]:
#copied the tensor to the cpu because numpy doesn't work with GPU's
tensor_on_gpu = tensor.cpu()
tensor_on_gpu.numpy() 

array([1, 3, 4])

## explore Assignment  


1. device diagnostic code 
2. dtype and general problem in tensors
3. try out pytorch inbuilt function
4. try out to try new thing with google 
5. view and reshape
6. stacking hstack, vstack
7. squeeze and unsqueeze
8. permuted didn't change as original (error fix it)
9. check how changing one can change other data
10. reproduclibility
11. setup 
12. cuda
13. why use many cpu gpu

In [205]:
# Dot product
import torch
torch.inner(torch.tensor([1,2,3]),torch.tensor([0,2,1]))


tensor(7)

In [206]:
# Multidemensional input tensors
a = torch.randn(size=(2,3))
a

tensor([[-0.3004, -1.1463,  2.2173],
        [-1.1345,  0.4725, -1.3764]])

In [207]:
b = torch.randn(2,4,3)
b

tensor([[[ 0.6702,  0.9178,  0.9622],
         [ 0.1585,  0.0479,  0.2299],
         [-0.7861, -0.4396,  0.5651],
         [ 0.7129, -1.1598, -0.5008]],

        [[ 0.5952,  0.0851, -0.4060],
         [-0.5512,  0.9348, -1.1235],
         [ 0.2869, -1.1786, -0.1861],
         [-0.9580, -1.1800,  1.3241]]])

In [208]:
# to do inner product, the size of their last dimension must match
torch.inner(a,b)

tensor([[[ 0.8799,  0.4073,  1.9930,  0.0050],
         [-1.1766, -3.3970,  0.8523,  4.5763]],

        [[-1.6510, -0.4736, -0.0936, -0.6675],
         [-0.0762,  2.6133, -0.6261, -1.2931]]])

In [209]:
# scalar input
torch.inner(a, torch.tensor(2))

tensor([[-0.6008, -2.2926,  4.4345],
        [-2.2690,  0.9449, -2.7528]])

In [210]:
# tensor views
t = torch.randn(4,4)
b = t.view(2,8)
print("t-tensor: ",t)
print(f"the view of the t tensor \n having shape: {b.shape} \n and dimension: {b.ndim}\n : {b}")

t-tensor:  tensor([[-0.1140,  0.1567, -2.1658,  1.7045],
        [ 0.7606,  2.2150, -0.0693, -0.2584],
        [ 0.5535,  1.4925,  0.2759,  0.1840],
        [-0.9891,  0.0053,  0.8823, -0.8039]])
the view of the t tensor 
 having shape: torch.Size([2, 8]) 
 and dimension: 2
 : tensor([[-0.1140,  0.1567, -2.1658,  1.7045,  0.7606,  2.2150, -0.0693, -0.2584],
        [ 0.5535,  1.4925,  0.2759,  0.1840, -0.9891,  0.0053,  0.8823, -0.8039]])


In [211]:
# 't' and 'b' share the same underlying data.
t.storage().data_ptr() == b.storage().data_ptr()


True

In [212]:
# modifying view sensor changes the base tensor as well
b[0][0] =3.14
t[0][0]

tensor(3.1400)

In [213]:
x = torch.ones(2,1,2,1,2)
y = torch.squeeze(x)
x.shape, y.shape
x.is_contiguous(), y.is_contiguous()
x,y*2

(tensor([[[[[1., 1.]],
 
           [[1., 1.]]]],
 
 
 
         [[[[1., 1.]],
 
           [[1., 1.]]]]]), tensor([[[2., 2.],
          [2., 2.]],
 
         [[2., 2.],
          [2., 2.]]]))

In [214]:
#creating a range and tensor like
import torch
# creating range of value 0 to 10
z = torch.arange(0,100,10)
z

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [215]:
# using to() will create copies to avoid the copies use requires_grad_()
z.to(dtype=torch.float16).requires_grad_()
z.dtype

torch.int64

In [216]:
tensor = torch.tensor([1,2,3,4,5,6],dtype=torch.float32, requires_grad=True)
out = tensor.pow(2).sum()
out.backward()
tensor.grad

tensor([ 2.,  4.,  6.,  8., 10., 12.])

In [217]:
# vector x vector
tensor1 = torch.rand(3)
tensor2 = torch.rand(3)
torch.matmul(tensor1,tensor2).size()

torch.Size([])

#### inner dimension broadcasting

In [218]:
# matrix x vector
tensor1 = torch.randn(3,4)
tensor2 = torch.randn(4)
print(f"tensor1: {tensor1} \n tensor1 size: {tensor1.size()}")
print(f"tensor2: {tensor2} \n tensor1 size: {tensor2.size()}")
print(f"matrix * vector: {torch.matmul(tensor1,tensor2)} \n size: {torch.matmul(tensor1,tensor2).size()}")


tensor1: tensor([[-0.1539,  0.0775, -0.1298, -0.2275],
        [-1.7822,  0.0453,  0.6322,  0.5371],
        [-0.2426,  1.4826,  0.4890, -1.5933]]) 
 tensor1 size: torch.Size([3, 4])
tensor2: tensor([-1.0278,  1.4589, -0.6138,  0.9292]) 
 tensor1 size: torch.Size([4])
matrix * vector: tensor([0.1395, 2.0089, 0.6317]) 
 size: torch.Size([3])


In [219]:
# batch matrix x broadcast vector
tensor1 = torch.randn(10,3,4)
tensor2 = torch.randn(4)
torch.matmul(tensor1,tensor2).size()


torch.Size([10, 3])

In [220]:
# batch matrix x batch matrix 
tensor1 = torch.randn(10,2,3,3,4)
tensor2 = torch.randn(10,2,1,4,5)
torch.matmul(tensor1,tensor2).size() 
# here the inner dimension (3,4) and (4,5) follows the mutliplication matrix rules
# 1. inner dimension must be same 2. the size of the matrix will be the outer dimensions
# i.e, (3,5) but since we are broadcasting on 10 so, we get (10,3,5)

torch.Size([10, 2, 3, 3, 5])

In [222]:
# broadcasting happens on the dimension 1 
# let's consider the example
t1 = torch.randn(500,2)
t2 = torch.randn(500,500)
torch.add(t1,t2).size() # it broadcast on 500 

RuntimeError: ignored

In [223]:
# let's consider the same example with 2 dimension
t1 = torch.randn(500,1)
t2 = torch.randn(500,500)
torch.add(t1,t2).size() 
# it fails to broadcast non-singleton dimension 2 if it were 1 
# it would broadcast it
# therefore, we get error below

torch.Size([500, 500])

In [224]:
# same goes for matmul too
# batch matrix x batch matrix 
tensor1 = torch.randn(10,2,3,3,4)
tensor2 = torch.randn(10,2,2,4,5) # changing 1 to 2
torch.matmul(tensor1,tensor2).size() 
# now we get the error since it do not known how to broadcast on 2 with 3

RuntimeError: ignored

#### Linear Layer

In [229]:
#  making reproducible
torch.manual_seed(42)
# This uses matmul
XtensorA = torch.randn(3,2)
linear = torch.nn.Linear(in_features = 4, # N= matches inner dimension
                         out_features = 180
                        ) # H = describes outer dimension
                        
x = tensor1
output = linear(x)
print(f'Input shape: {x.shape} \n')
print(f'Output:\n{output}\n\n output shape:{output.shape}')

In [230]:
t = torch.arange(1,100,9)
t.type(torch.float32).mean()
torch.mean(t.type(torch.float32))
# mean won't work without float datatype

tensor(46.)

In [231]:
stacked = torch.stack([t,t,t,t], dim=1
                      )
stacked = stacked.squeeze()
stacked

tensor([[ 1,  1,  1,  1],
        [10, 10, 10, 10],
        [19, 19, 19, 19],
        [28, 28, 28, 28],
        [37, 37, 37, 37],
        [46, 46, 46, 46],
        [55, 55, 55, 55],
        [64, 64, 64, 64],
        [73, 73, 73, 73],
        [82, 82, 82, 82],
        [91, 91, 91, 91]])

In [232]:
# reshaping 
import torch
a = torch.arange(4.)
torch.reshape(a,(2,2))


tensor([[0., 1.],
        [2., 3.]])

In [233]:
b = torch.tensor([[0,1],[2,3]])
torch.reshape(b,(-1,))

tensor([0, 1, 2, 3])

In [237]:
x = torch.randn(4,4)
x.size()

torch.Size([4, 4])

### Tensor.View
Returns a new tensor with the same data as the self tensor but of a different shape.



In [239]:
x

tensor([[-0.7295,  0.4308,  0.2862, -0.2481],
        [ 0.2040, -0.5630, -0.2829,  0.0731],
        [-0.8018,  0.2771,  2.5599, -1.6952],
        [ 0.1885,  0.4360, -1.4770, -1.2222]])

In [242]:
# torch.tensor.view
print(f"size of original tensor: {x.size()}")
y = x.view(16) 
print(f"size of y view: {y.size()} , \n how it look :{y} \n")
# The way we let PyTorch know that we don't know what the last number should be is we pass in a -1.
z = x.view(-1,2)
b = x.view(4,-1) # size -1 is inferred from other dimensions, which says idon't know 
# what dimension to get, so pytorch do it for me
print(f"size of z view: {z.size()}, \n how it look :{z}\n")
print(f"size of b view: {b.size()}, \n how it look : {b}\n")

size of original tensor: torch.Size([4, 4])
size of y view: torch.Size([16]) , 
 how it look :tensor([-0.7295,  0.4308,  0.2862, -0.2481,  0.2040, -0.5630, -0.2829,  0.0731,
        -0.8018,  0.2771,  2.5599, -1.6952,  0.1885,  0.4360, -1.4770, -1.2222]) 

size of z view: torch.Size([8, 2]), 
 how it look :tensor([[-0.7295,  0.4308],
        [ 0.2862, -0.2481],
        [ 0.2040, -0.5630],
        [-0.2829,  0.0731],
        [-0.8018,  0.2771],
        [ 2.5599, -1.6952],
        [ 0.1885,  0.4360],
        [-1.4770, -1.2222]])

size of b view: torch.Size([4, 4]), 
 how it look : tensor([[-0.7295,  0.4308,  0.2862, -0.2481],
        [ 0.2040, -0.5630, -0.2829,  0.0731],
        [-0.8018,  0.2771,  2.5599, -1.6952],
        [ 0.1885,  0.4360, -1.4770, -1.2222]])



In [243]:
# view(dtype)
x = torch.randn(4,4)
print(f"tensor x: {x}\n")
print(f"\ndata type for tensor x : {x.dtype}")

tensor x: tensor([[-0.2415,  1.3204,  1.5997, -1.0792],
        [-0.3396, -1.4538, -2.6740,  1.5984],
        [ 1.2068,  0.5722,  0.0653, -0.0235],
        [ 0.8876,  1.4689,  1.2647, -0.2753]])


data type for tensor x : torch.float32


In [244]:
y = x.view(torch.int32)
print(f"view tensor y: {y}\n")
print(f"\ndata type for tensor y : {y.dtype}")

view tensor y: tensor([[-1099478973,  1068041323,  1070383839, -1081465695],
        [-1095900844, -1078323605, -1070914835,  1070372698],
        [ 1067087984,  1058175542,  1032173084, -1128256222],
        [ 1063467552,  1069286662,  1067573667, -1098059595]],
       dtype=torch.int32)


data type for tensor y : torch.int32


In [245]:
x
print(f"size of float32 default tensor: {x.size()}")
print(f"size of x.view for cfloat dtype tensor: {x.view(torch.cfloat).size()}")
print(f"size of x.view for uint8 dtype tensor: {x.view(torch.uint8).size()}")
print(f"size of x.view for bool dtype tensor: {x.view(torch.bool).size()}")
print(f"size of x.view for float16 dtype tensor: {x.view(torch.float16).size()},\nwhen precision in important at expense\n")
print(f"size of x.view for bfloat16 dtype tensor: {x.view(torch.bfloat16).size()}")
print(f"size of x.view for complex double dtype tensor: {x.view(torch.cdouble).size()}, \nbrain floating useful when range is important at expense")


size of float32 default tensor: torch.Size([4, 4])
size of x.view for cfloat dtype tensor: torch.Size([4, 2])
size of x.view for uint8 dtype tensor: torch.Size([4, 16])
size of x.view for bool dtype tensor: torch.Size([4, 16])
size of x.view for float16 dtype tensor: torch.Size([4, 8]),
when precision in important at expense

size of x.view for bfloat16 dtype tensor: torch.Size([4, 8])
size of x.view for complex double dtype tensor: torch.Size([4, 1]), 
brain floating useful when range is important at expense


### unsqueeze

Returns a new tensor with a dimension of size one inserted at the specified position.



In [247]:
x = torch.tensor([1,2,3,4])
print(f"dimension of TESNOR and TENSOR: {x.ndim, x}")
print(f'unsqueeze the tensor along 0: {torch.unsqueeze(x,0)}, \nmaking it: {torch.unsqueeze(x,0).ndim}d')
print(f'unsqueeze the tensor along 1: {torch.unsqueeze(x,1)} \nmaking it: {torch.unsqueeze(x,1).ndim}d')

dimension of TESNOR and TENSOR: (1, tensor([1, 2, 3, 4]))
unsqueeze the tensor along 0: tensor([[1, 2, 3, 4]]), 
making it: 2d
unsqueeze the tensor along 1: tensor([[1],
        [2],
        [3],
        [4]]) 
making it: 2d


### TORCH.PERMUTE
Returns a view of the original tensor input with its dimensions rearranged

In [248]:
x = torch.randn(2,3,5)
print(f'dimension of the orignal tensor :{x.size()}')
print(f'dimension of the view permuted 0->2 1->0 2->1: {torch.permute(x,(2,0,1)).size()}')

dimension of the orignal tensor :torch.Size([2, 3, 5])
dimension of the view permuted 0->2 1->0 2->1: torch.Size([5, 2, 3])


#### pyTorch tensors & NumPy


In [249]:
import numpy
a = numpy.array([1,2,3])
t = torch.from_numpy(a)
t[0] = -1 # changing tensor changes the ndarray too.
a

array([-1,  2,  3])

In [250]:
# by default we need float32 but numpy uses 64 
# so we need to convert
t = torch.from_numpy(a).type(torch.float32)
t.dtype


torch.float32

In [251]:
# change the array, keep the tensor
a = a+1
a, t

(array([0, 3, 4]), tensor([-1.,  2.,  3.]))

In [252]:
#tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [253]:
# now if we change the tensor the following numpy remains same
tensor = tensor + 1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [254]:
import torch
import random 

RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
tensor = torch.randn(3,4)
tensor

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])

In [255]:
!nvidia-smi

Fri Sep 23 18:38:56 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P0    32W /  70W |    610MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [256]:
# check for GPU
import torch
torch.cuda.is_available()


True

In [257]:
# set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [258]:
# Count number of devices
torch.cuda.device_count()

1

In [259]:
# reassign tensor (default on CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to. GPU(if available)
tensor_on_GPU = tensor.to(device)
tensor_on_GPU

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [260]:
# moving back tensor on CPU
# why? : to interact with numpy coz numpy does not leverage GPU
tensor_cpu = tensor_on_GPU.cpu()
tensor_cpu.device

device(type='cpu')

In [261]:
import argparse
import torch

parser = argparse.ArgumentParser(description='PyTorch Example')
parser.add_argument('--disable-cuda', action='store_true',
                    help='Disable CUDA')
args = parser.parse_args()
args.device = None
if not args.disable_cuda and torch.cuda.is_available():
    args.device = torch.device('cuda')
else:
    args.device = torch.device('cpu')

usage: ipykernel_launcher.py [-h] [--disable-cuda]
ipykernel_launcher.py: error: unrecognized arguments: -f /root/.local/share/jupyter/runtime/kernel-02144f8f-8580-4d9f-a7a2-0ab955310924.json


SystemExit: ignored

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [262]:
# creating random tensor 
random_seed = 0
torch.manual_seed(seed=random_seed)
tensor = torch.rand(3,4)
tensor2 = torch.randn(4,3)
torch.matmul(tensor2,tensor)

tensor([[ 0.1301,  0.3864,  0.1955,  0.5156],
        [-0.3006, -0.5731, -0.2646, -0.5150],
        [-0.5748, -0.6376,  0.0899,  0.4432],
        [ 0.0568, -0.0289, -0.1365, -0.3416]])

In [263]:
torch.manual_seed(seed=random_seed)

ten_2 = torch.randn(1,7)
ten_3 = torch.randn(1,7)
print(ten_2)
print(ten_3)
print(f"multiplication of tensors\n {ten_3.T @ ten_2}")

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986,  0.4033]])
tensor([[ 0.8380, -0.7193, -0.4033, -0.5966,  0.1820, -0.8567,  1.1006]])
multiplication of tensors
 tensor([[ 1.2914, -0.2459, -1.8259,  0.4764, -0.9089, -1.1721,  0.3380],
        [-1.1084,  0.2111,  1.5671, -0.4088,  0.7801,  1.0060, -0.2901],
        [-0.6216,  0.1184,  0.8788, -0.2293,  0.4374,  0.5641, -0.1627],
        [-0.9194,  0.1751,  1.2999, -0.3391,  0.6471,  0.8345, -0.2407],
        [ 0.2805, -0.0534, -0.3966,  0.1035, -0.1974, -0.2546,  0.0734],
        [-1.3201,  0.2514,  1.8665, -0.4870,  0.9291,  1.1981, -0.3455],
        [ 1.6960, -0.3229, -2.3980,  0.6256, -1.1936, -1.5393,  0.4439]])


In [264]:
torch.cuda.manual_seed(1234)

In [265]:
torch.manual_seed(1234)
tensor1 = torch.rand(2,3)
torch.manual_seed(1234)
tensor2 = torch.rand(2,3)
tensor1.to(device),tensor2.to(device)

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [266]:
print(f'minimum and maximum: {torch.matmul(tensor1,tensor2.T).min(),torch.matmul(tensor1,tensor2.T).max()}')
print(f'index value of min and max: {torch.matmul(tensor1,tensor2.T).argmin().item(),torch.matmul(tensor1,tensor2.T).argmax().item()}')


minimum and maximum: (tensor(0.2161), tensor(0.6287))
index value of min and max: (1, 3)


In [267]:
tensor = torch.randn(1,1,1,10)
tensor_new = torch.squeeze(tensor)
tensor_new.shape

torch.Size([10])

In [268]:
torch.rand(2)
torch.rand(1,7).ndim

2